"""Pydantic models for the CyberCity digital-twin network model.

Schema goals for v3.0:
  * Declarative layer describes topology: organizations, network roles, services,
    and links. Concrete IP addressing is generated by the allocator.
  * org_id is still injected by the loader to avoid repeating it in every service.
  * Mock services (`decoy` block) are ordinary services marked as simulation-only.
  * `extra="forbid"` keeps typos loud.
"""

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "OrgKind",
    "SvcKind",
    "Exposure",
    "NetworkKind",
    "AuthMethod",
    "DataClassification",
    "Software",
    "Criticality",
    "LinkKind",
    "LinkEncryption",
    "DecoyKind",
    "DecoyFingerprint",
    "Network",
    "Organization",
    "Service",
    "Link",
    "CityNetwork",
    "SCHEMA_VERSION",
]

# ─────────────────────────────────────────────────────────────────────
# Schema version
# ─────────────────────────────────────────────────────────────────────
SCHEMA_VERSION = "3.0.0"

# ─────────────────────────────────────────────────────────────────────
# Enums (Literal — pydantic emits a clear error on a bad value)
# ─────────────────────────────────────────────────────────────────────
OrgKind = Literal[
    "government",
    "healthcare",
    "infra-utilities",
    "finance",
    "retail",
    "media-telecom",
    "education",
    "msp",
]

SvcKind = Literal[
    "web",
    "api",
    "pos",
    "identity",
    "db",
    "file-share",
    "rmm",
    "vpn",
    "ot",
    "cctv",
    "mail",
    "dns",
    "ntp",
    "backup",
    "log",
    "erp",
    "hrms",
    "billing",
    "tickets",
    "wiki",
    "crm",
    "pharmacy-front",
    "iot",
]

Exposure = Literal["public", "intranet", "ot", "mgmt"]

NetworkKind = Literal["dmz", "lan", "ot", "mgmt", "internet"]

AuthMethod = Literal["none", "local", "sso", "mfa", "certificate"]

DataClassification = Literal[
    "public",
    "internal",
    "confidential",
    "restricted",
    "pii",
    "phi",
    "pci",
]

Criticality = Literal[
    "critical",
    "high",
    "medium",
    "low",
]

LinkKind = Literal[
    "api-call",
    "auth",
    "db-read",
    "db-write",
    "log-sink",
    "backup-of",
    "trusts",
    "vendor-vpn",
    "dns-query",
    "ntp-query",
]

LinkEncryption = Literal["none", "tls", "mtls", "ipsec", "sso-trust"]

DecoyKind = Literal[
    "http",
    "ssh",
    "rdp",
    "printer",
    "iot",
    "nas",
    "camera",
    "random",
]

DecoyFingerprint = Literal[
    "realistic",
    "default-creds",
    "known-cve",
    "decoy-banner",
]

# ─────────────────────────────────────────────────────────────────────
# Patterns
# ─────────────────────────────────────────────────────────────────────
_KEBAB = r"^[a-z][a-z0-9-]*$"
_SEMVER = r"^\d+\.\d+\.\d+$"
_PORT = r"^(tcp|udp)/(6553[0-5]|655[0-2]\d|65[0-4]\d\d|6[0-4]\d{3}|[1-5]\d{4}|[1-9]\d{0,3})$"
_FQDN = r"^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$"
_SOFTWARE_VERSION = r"^(\d+(\.\d+){0,3}(-[\w.]+)?|unknown|any)$"
_CVE = r"^CVE-\d{4}-\d{4,}$"


# ─────────────────────────────────────────────────────────────────────
# Base model
# ─────────────────────────────────────────────────────────────────────
class _StrictModel(BaseModel):
    """Common config: forbid unknown fields, validate on assignment."""

    model_config = ConfigDict(extra="forbid", validate_assignment=True)


# ─────────────────────────────────────────────────────────────────────
# Network (first-class in v2.0)
# ─────────────────────────────────────────────────────────────────────
class Network(_StrictModel):
    """A layer-3 network that belongs to exactly one organization.

    The concrete CIDR is generated by the allocator from the network ``kind``.
    """

    id: str = Field(pattern=_KEBAB)
    org_id: str = Field(pattern=_KEBAB)
    name: str | None = None
    kind: NetworkKind
    description: str | None = None


# ─────────────────────────────────────────────────────────────────────
# Supporting models
# ─────────────────────────────────────────────────────────────────────
class Software(_StrictModel):
    """Product fingerprint for a service."""

    vendor: str
    product: str
    version: str | None = Field(default=None, pattern=_SOFTWARE_VERSION)
    cve_id: str | None = Field(default=None, pattern=_CVE)


class DecoyBlock(_StrictModel):
    """Marks a service as a simulation-only / mock service."""

    kind: DecoyKind = "http"
    fingerprint: DecoyFingerprint = "realistic"
    os_hint: str | None = None
    note: str | None = None


# ─────────────────────────────────────────────────────────────────────
# Organization
# ─────────────────────────────────────────────────────────────────────
class Organization(_StrictModel):
    id: str = Field(pattern=_KEBAB)
    name: str
    kind: OrgKind

    description: str | None = None

    # Networks must be declared explicitly in v3.0.  Their concrete addressing is generated.
    networks: list[Network] = []


# ─────────────────────────────────────────────────────────────────────
# Service
# ─────────────────────────────────────────────────────────────────────
class Service(_StrictModel):
    id: str = Field(pattern=_KEBAB)
    org_id: str = Field(pattern=_KEBAB)
    name: str
    description: str | None = None
    kind: SvcKind
    exposure: Exposure
    host: str = Field(pattern=_FQDN)

    # Logical network placement must be declared explicitly in v3.0.
    # The concrete bind_ip is generated by the allocator.
    network_id: str | None = Field(default=None, pattern=_KEBAB)

    software: Software | None = None
    os_hint: str | None = None
    auth: AuthMethod = "local"
    data_classification: DataClassification = "internal"
    criticality: Criticality = "medium"
    ports: list[Annotated[str, Field(pattern=_PORT)]] = Field(default_factory=list)
    decoy: DecoyBlock | None = None


# ─────────────────────────────────────────────────────────────────────
# Link
# ─────────────────────────────────────────────────────────────────────
class Link(_StrictModel):
    from_service: str = Field(pattern=_KEBAB)
    to_service: str = Field(pattern=_KEBAB)
    kind: LinkKind
    protocol: str | None = Field(default=None, pattern=_PORT)

    encryption: LinkEncryption = "tls"
    label: str | None = None


# ─────────────────────────────────────────────────────────────────────
# Root model
# ─────────────────────────────────────────────────────────────────────
class CityNetwork(_StrictModel):
    """Assembled city: organizations, services, links."""

    version: str = Field(default=SCHEMA_VERSION, pattern=_SEMVER)
    organizations: list[Organization] = []
    services: list[Service] = []
    links: list[Link] = []
